{% set version = "2.0.4" %}

package:
  name: portmidi
  version: {{ version }}

source:
  url: https://github.com/PortMidi/portmidi/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64893e823ae146cabd3ad7f9a9a9c5332746abe7847c557b99b2577afa8a607c

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("portmidi", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - alsa-lib  # [linux]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/libportmidi.so              # [linux]
    - test -f $PREFIX/lib/libportmidi.dylib           # [osx]
    - if not exist %LIBRARY_BIN%\portmidi.dll exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libportmidi.a             # [not win]

    # headers
    - test -f $PREFIX/include/portmidi.h              # [unix]
    - test -f $PREFIX/include/porttime.h              # [unix]
    - if not exist %LIBRARY_INC%\portmidi.h exit 1    # [win]
    - if not exist %LIBRARY_INC%\porttime.h exit 1    # [win]

about:
  home: https://github.com/PortMidi/portmidi
  license: MIT
  license_file: license.txt
  summary: portmidi is a cross-platform MIDI input/output library
  dev_url: https://github.com/PortMidi/portmidi
  doc_url: https://portmidi.github.io/portmidi_docs/

extra:
  recipe-maintainers:
    - h-vetinari
